import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import StandardNavigation from "@/components/standard-navigation"
import StandardFooter from "@/components/standard-footer"
import { 
  Star, 
  Quote, 
  Users, 
  Globe, 
  TrendingUp,
  CheckCircle,
  Play
} from "lucide-react"

export const metadata = {
  title: "Client Testimonials & Success Stories - Mindscape Global Formations",
  description: "Read real testimonials from our satisfied clients. See how we've helped 10,000+ entrepreneurs successfully form their LLCs and grow their businesses.",
}

export default function TestimonialsPage() {
  const testimonials = [
    {
      name: "Sarah Chen",
      location: "Singapore",
      business: "E-commerce Store",
      rating: 5,
      text: "Mindscape Global Formations made the entire LLC formation process incredibly smooth. From initial consultation to getting my bank account set up, they guided me every step of the way. My business is now thriving on Amazon and eBay!",
      revenue: "$15,000/month",
      timeframe: "6 months",
      image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
      featured: true
    },
    {
      name: "Ahmed Hassan",
      location: "Dubai, UAE",
      business: "Digital Marketing Agency",
      rating: 5,
      text: "As a freelancer looking to scale, I needed a U.S. LLC to work with American clients. The team at Mindscape Global Formations not only formed my LLC quickly but also helped me understand the tax implications and business structure. Highly recommended!",
      revenue: "$8,500/month",
      timeframe: "4 months",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
      featured: true
    },
    {
      name: "Maria Rodriguez",
      location: "Mexico City",
      business: "Online Course Platform",
      rating: 5,
      text: "The premium package was worth every penny. Not only did I get my LLC formed, but the business training sessions helped me understand how to scale my online course business. The PayPal and Stripe setup was seamless.",
      revenue: "$12,000/month",
      timeframe: "8 months",
      image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
      featured: false
    },
    {
      name: "David Kim",
      location: "Seoul, South Korea",
      business: "SaaS Application",
      rating: 5,
      text: "I was skeptical about forming an LLC from overseas, but Mindscape Global Formations made it so easy. Their support team was always available via WhatsApp, and they explained everything in detail. My SaaS business is now generating $25K monthly revenue.",
      revenue: "$25,000/month",
      timeframe: "12 months",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
      featured: false
    },
    {
      name: "Priya Patel",
      location: "Mumbai, India",
      business: "Consulting Services",
      rating: 5,
      text: "The team's expertise in business formation is unmatched. They helped me choose the right state (Wyoming) for my consulting business and provided ongoing support even after formation. The bank account setup was surprisingly quick!",
      revenue: "$18,000/month",
      timeframe: "10 months",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
      featured: false
    },
    {
      name: "James Thompson",
      location: "London, UK",
      business: "Real Estate Investment",
      rating: 5,
      text: "I needed a U.S. LLC for my real estate investments. Mindscape Global Formations handled everything professionally and quickly. The registered agent service and ongoing compliance support have been invaluable.",
      revenue: "$35,000/month",
      timeframe: "18 months",
      image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
      featured: false
    }
  ]

  const successStats = [
    {
      icon: Users,
      number: "10,000+",
      label: "Happy Clients",
      description: "Entrepreneurs worldwide trust us"
    },
    {
      icon: Star,
      number: "4.9/5",
      label: "Average Rating",
      description: "Based on verified reviews"
    },
    {
      icon: Globe,
      number: "50+",
      label: "Countries Served",
      description: "Global reach, local expertise"
    },
    {
      icon: TrendingUp,
      number: "$2.5M+",
      label: "Client Revenue",
      description: "Generated by our clients monthly"
    }
  ]

  const caseStudies = [
    {
      title: "From Freelancer to $50K/Month E-commerce Empire",
      client: "Sarah Chen",
      location: "Singapore",
      challenge: "Wanted to scale from freelancing to e-commerce but needed proper business structure",
      solution: "LLC formation + bank account + payment processing + Amazon FBA training",
      results: [
        "LLC formed in 24 hours",
        "Bank account opened in 3 days",
        "PayPal and Stripe setup completed",
        "Amazon FBA store launched successfully",
        "Revenue grew from $2K to $50K/month in 8 months"
      ],
      testimonial: "Mindscape Global Formations didn't just form my LLC - they gave me the roadmap to build a successful e-commerce business. The training sessions were game-changing!",
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop"
    },
    {
      title: "Digital Agency Scales to $30K/Month with U.S. LLC",
      client: "Ahmed Hassan",
      location: "Dubai, UAE",
      challenge: "Needed U.S. business presence to work with American clients and access better payment processing",
      solution: "LLC formation + EIN + business bank account + payment processor setup",
      results: [
        "LLC formed in Wyoming for business-friendly laws",
        "EIN obtained same day",
        "Business bank account with major U.S. bank",
        "Stripe merchant account approved",
        "Client base expanded to include Fortune 500 companies"
      ],
      testimonial: "The U.S. LLC opened doors I never thought possible. American clients trust us more, and we can now accept payments seamlessly. Revenue increased 300% in 6 months.",
      image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=400&fit=crop"
    }
  ]

  return (
    <div className="min-h-screen">
      {/* USA Flag Accent */}
      <div className="usa-flag-accent"></div>
      
      {/* Standardized Navigation */}
      <StandardNavigation currentPage="/testimonials" />

      {/* Hero Section */}
      <section className="py-20 bg-gradient-to-br from-muted/30 to-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <Badge className="mb-6 bg-accent text-white">Client Success Stories</Badge>
          <h1 className="text-4xl md:text-5xl font-bold mb-6 font-[family-name:var(--font-space-grotesk)]">
            Real Results from Real Clients
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto font-[family-name:var(--font-dm-sans)]">
            See how we've helped thousands of entrepreneurs worldwide establish their U.S. businesses and achieve remarkable success.
          </p>
        </div>
      </section>

      {/* Success Stats */}
      <section className="py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-4 gap-8">
            {successStats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="w-16 h-16 bg-accent/10 rounded-2xl flex items-center justify-center mx-auto mb-4">
                  <stat.icon className="w-8 h-8 text-accent" />
                </div>
                <div className="text-3xl font-bold text-primary mb-2">{stat.number}</div>
                <div className="font-semibold mb-1 font-[family-name:var(--font-space-grotesk)]">{stat.label}</div>
                <div className="text-sm text-muted-foreground font-[family-name:var(--font-dm-sans)]">{stat.description}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Featured Testimonials */}
      <section className="py-20 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 font-[family-name:var(--font-space-grotesk)]">
              Featured Success Stories
            </h2>
            <p className="text-xl text-muted-foreground font-[family-name:var(--font-dm-sans)]">
              Real entrepreneurs sharing their journey to success
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8 mb-16">
            {testimonials.filter(t => t.featured).map((testimonial, index) => (
              <Card key={index} className="trust-shadow border-0 relative overflow-hidden">
                <div className="absolute top-4 right-4 bg-accent text-white text-xs px-2 py-1 rounded-full font-bold">
                  Featured
                </div>
                <CardHeader>
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-16 h-16 bg-gradient-to-br from-primary/10 to-accent/10 rounded-full flex items-center justify-center">
                      <img
                        src={testimonial.image}
                        alt={testimonial.name}
                        className="w-14 h-14 rounded-full object-cover"
                      />
                    </div>
                    <div>
                      <CardTitle className="font-[family-name:var(--font-space-grotesk)]">{testimonial.name}</CardTitle>
                      <CardDescription className="font-[family-name:var(--font-dm-sans)]">
                        {testimonial.business} • {testimonial.location}
                      </CardDescription>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="w-5 h-5 fill-accent text-accent" />
                    ))}
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="relative mb-6">
                    <Quote className="absolute -top-2 -left-2 w-8 h-8 text-accent/30" />
                    <p className="text-muted-foreground font-[family-name:var(--font-dm-sans)] text-lg leading-relaxed pl-6">
                      "{testimonial.text}"
                    </p>
                  </div>
                  <div className="grid grid-cols-2 gap-4 pt-4 border-t border-border">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-accent">{testimonial.revenue}</div>
                      <div className="text-sm text-muted-foreground font-[family-name:var(--font-dm-sans)]">Monthly Revenue</div>
                    </div>
                    <div className="text-center">
                      <div className="text-2xl font-bold text-accent">{testimonial.timeframe}</div>
                      <div className="text-sm text-muted-foreground font-[family-name:var(--font-dm-sans)]">Time to Success</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* All Testimonials */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 font-[family-name:var(--font-space-grotesk)]">
              What Our Clients Say
            </h2>
            <p className="text-xl text-muted-foreground font-[family-name:var(--font-dm-sans)]">
              Honest feedback from entrepreneurs who've built successful businesses with us
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card key={index} className="trust-shadow border-0">
                <CardHeader>
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 bg-gradient-to-br from-primary/10 to-accent/10 rounded-full flex items-center justify-center">
                      <img
                        src={testimonial.image}
                        alt={testimonial.name}
                        className="w-10 h-10 rounded-full object-cover"
                      />
                    </div>
                    <div>
                      <CardTitle className="text-lg font-[family-name:var(--font-space-grotesk)]">{testimonial.name}</CardTitle>
                      <CardDescription className="font-[family-name:var(--font-dm-sans)] text-sm">
                        {testimonial.location}
                      </CardDescription>
                    </div>
                  </div>
                  <div className="flex items-center gap-1 mb-3">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-accent text-accent" />
                    ))}
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground font-[family-name:var(--font-dm-sans)] text-sm leading-relaxed mb-4">
                    "{testimonial.text}"
                  </p>
                  <div className="flex items-center justify-between text-sm">
                    <div>
                      <div className="font-semibold text-accent">{testimonial.revenue}</div>
                      <div className="text-muted-foreground font-[family-name:var(--font-dm-sans)]">Monthly Revenue</div>
                    </div>
                    <div>
                      <div className="font-semibold text-accent">{testimonial.timeframe}</div>
                      <div className="text-muted-foreground font-[family-name:var(--font-dm-sans)]">Time to Success</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Case Studies */}
      <section className="py-20 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 font-[family-name:var(--font-space-grotesk)]">
              Detailed Case Studies
            </h2>
            <p className="text-xl text-muted-foreground font-[family-name:var(--font-dm-sans)]">
              In-depth look at how we've helped clients achieve remarkable success
            </p>
          </div>

          <div className="space-y-16">
            {caseStudies.map((study, index) => (
              <Card key={index} className="trust-shadow border-0 overflow-hidden">
                <div className="grid lg:grid-cols-2 gap-0">
                  <div className="relative h-64 lg:h-auto">
                    <img
                      src={study.image}
                      alt={study.title}
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                    <div className="absolute bottom-4 left-4 text-white">
                      <div className="text-sm font-semibold">{study.client}</div>
                      <div className="text-xs opacity-90">{study.location}</div>
                    </div>
                  </div>
                  <div className="p-8">
                    <Badge className="mb-4 bg-accent text-white">Case Study</Badge>
                    <CardTitle className="text-2xl mb-4 font-[family-name:var(--font-space-grotesk)]">
                      {study.title}
                    </CardTitle>
                    
                    <div className="space-y-4 mb-6">
                      <div>
                        <h4 className="font-semibold mb-2 text-accent">Challenge:</h4>
                        <p className="text-muted-foreground font-[family-name:var(--font-dm-sans)] text-sm">
                          {study.challenge}
                        </p>
                      </div>
                      <div>
                        <h4 className="font-semibold mb-2 text-accent">Solution:</h4>
                        <p className="text-muted-foreground font-[family-name:var(--font-dm-sans)] text-sm">
                          {study.solution}
                        </p>
                      </div>
                    </div>

                    <div className="mb-6">
                      <h4 className="font-semibold mb-3 text-accent">Results:</h4>
                      <div className="space-y-2">
                        {study.results.map((result, resultIndex) => (
                          <div key={resultIndex} className="flex items-center gap-2">
                            <CheckCircle className="w-4 h-4 text-accent flex-shrink-0" />
                            <span className="text-sm font-[family-name:var(--font-dm-sans)]">{result}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="bg-accent/5 rounded-lg p-4 border border-accent/20">
                      <Quote className="w-6 h-6 text-accent mb-2" />
                      <p className="text-sm font-[family-name:var(--font-dm-sans)] italic">
                        "{study.testimonial}"
                      </p>
                    </div>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Video Testimonials */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 font-[family-name:var(--font-space-grotesk)]">
              Video Testimonials
            </h2>
            <p className="text-xl text-muted-foreground font-[family-name:var(--font-dm-sans)]">
              Hear directly from our clients about their experience
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[1, 2, 3].map((video, index) => (
              <Card key={index} className="trust-shadow border-0 overflow-hidden group cursor-pointer">
                <div className="relative h-48 bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
                  <div className="w-16 h-16 bg-white/90 rounded-full flex items-center justify-center group-hover:scale-110 transition-transform">
                    <Play className="w-8 h-8 text-primary ml-1" />
                  </div>
                </div>
                <CardContent className="p-6">
                  <CardTitle className="text-lg mb-2 font-[family-name:var(--font-space-grotesk)]">
                    Client Success Story #{video}
                  </CardTitle>
                  <CardDescription className="font-[family-name:var(--font-dm-sans)] text-sm">
                    Watch how we helped this entrepreneur build a successful business
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Standardized Footer */}
      <StandardFooter />
    </div>
  )
}
